export const FECTH_POSTS = 'FETCH_POSTS';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_FAILED = 'POSTS_FAILED';
export const POST_FEEDBACK = "POST_FEEDBACK";
export const USER_FEEDBACK = "USER_FEEDBACK";
export const MAIL_FEEDBACK = "MAIL_FEEDBACK";